export let gatherList = [
  {
    id: 1,
    savingMode: "군적금",
    goalName: "1000만원 모으기",
    category: "",
    currentAmount: 800000,
    goalAmount: 3600000,
    account: {
      bankName: "KB국민",
      productName: "KB 장병내일준비적금",
      accountNumber: "112-0330-0201",
      accountCurrentAmount: 0,
      bankImageUrl: "",
    },
    sDate: "Sun Oct 10 2021 15:11:39 GMT+0900",
    eDate: "Fri Mar 10 2023 23:59:59 GMT+0900",
    depositMethod: "자동이체",
    limitCycle: "매월 10일",
    amountPerCycle: 200000,
    transactions: [],
  },
  {
    id: 2,
    savingMode: "목표",
    goalName: "뉴욕여행 준비",
    category: "여행",
    currentAmount: 170000,
    goalAmount: 1000000,
    account: {
      bankName: "KEB 하나",
      productName: "KB 장병내일준비적금",
      accountNumber: "123-256-78-910111",
      accountCurrentAmount: 0,
      bankImageUrl: "",
    },
    sDate: "Wed Nov 10 2021 15:11:39 GMT+0900",
    eDate: "Sat Dec 10 2022 23:59:59 GMT+0900",
    depositMethod: "자동이체",
    limitCycle: "매월 10일",
    amountPerCycle: 50000,
    transactions: [],
  },
  {
    id: 3,
    savingMode: "비상금",
    goalName: "비상금 모으기",
    category: "",
    currentAmount: 100000,
    goalAmount: 0,
    account: {
      bankName: "KEB 하나",
      productName: "KB 장병내일준비적금",
      accountNumber: "123-356-78-910111",
      accountCurrentAmount: 0,
      bankImageUrl: "",
    },
    sDate: "Wed Nov 10 2021 15:11:39 GMT+0900",
    eDate: "Sat Dec 10 2022 23:59:59 GMT+0900",
    depositMethod: "",
    limitCycle: "",
    amountPerCycle: 0,
    transactions: [],
  },

  {
    id: 4,
    savingMode: "목표",
    goalName: "조카 선물😎",
    category: "선물",
    currentAmount: 150000,
    goalAmount: 150000,
    account: {
      bankName: "KEB 하나",
      productName: "KB 장병내일준비적금",
      accountNumber: "123-356-78-910111",
      accountCurrentAmount: 0,
      bankImageUrl: "",
    },
    sDate: "Wed Nov 10 2021 15:11:39 GMT+0900",
    eDate: "Wed Jan 26 2022 23:59:59 GMT+0900",
    depositMethod: "자유입금",
    limitCycle: "",
    amountPerCycle: 50000,
    transactions: [],
  },
];

export const accountList = [
  {
    id: 1,
    bankName: "KB국민",
    accountName: "KB나라사랑우대통장",
    accountNumber: "112-0330-0201",
    currentAmount: 500000,
    owner: "김민수",
    accountType: "예적금",
    bankImageUrl: "",
  },
  {
    id: 2,
    bankName: "KEB 하나",
    accountName: "하나장병내일준비적금",
    accountNumber: "110-0551-0031",
    currentAmount: 100000,
    owner: "김민수",
    accountType: "예적금",
    bankImageUrl: "",
  },
];

export const noticeList = [
  {
    id: 8,
    category: "penalty",
    date: "2월 02일",
    content:
      "‘신한 장병내일준비적금' 중도해지 패널티로 열쇠 6개가 차감되었어요",
  },
  {
    id: 7,
    category: "reward",
    date: "1월 30일",
    content: "야금야금MOA박스를 구매했어요",
  },
  {
    id: 6,
    category: "challenge",
    date: "1월 29일",
    content: "‘프리미어리그 경기 승자는?’ 챌린지 내기에 성공했어요!",
  },
  {
    id: 5,
    category: "key",
    date: "1월 28일",
    content: "첫 비상금 개설로 열쇠 3개를 획득했어요",
  },
  {
    id: 4,
    category: "account",
    date: "1월 28일",
    content: "첫 비상금을 개설했어요",
  },
  {
    id: 3,
    category: "key",
    date: "1월 28일",
    content: "첫 목표 ‘뉴욕여행 준비' 개설로 열쇠 3개를 획득했어요",
  },
  {
    id: 2,
    category: "key",
    date: "1월 28일",
    content: "첫 목표 ‘뉴욕여행 준비'를 개설했어요",
  },
  {
    id: 1,
    category: "key",
    date: "1월 27일",
    content: "첫 목표 ‘뉴욕여행 준비'를 개설했어요",
  },
];
