import moment from "moment";
import React, { createContext, useEffect, useState } from "react";
import { v1 as uuid } from "uuid";
export const BoxListData = createContext({
  boxList: [],
});
function BoxList({ children }) {
  const [boxList, setBoxList] = useState([]);
  useEffect(() => {
    getBoxList();
  }, []);
  function getBoxList() {
    setBoxList([
      {
        boxId: "",
        boxName: "MOA박스",
        boxPrice: 7,
        boxDescription: ["다양한 PX 간식", "(냉동 식품 제외)"],
        boxImageUrl: "",
        productList: [
          {
            productId: "",
            productName: "아카페라 라떼",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "포스틱",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "바나나킥",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "자갈치",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "칠성 사이다",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "바나나 우유",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "슈팅스타 콘",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "끌레도르콘 쿠키앤크림",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "불닭볶음면 컵라면",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "짜파게티 컵라면",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "오징어짬뽕 컵라면",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "몽쉘 딸기케이크",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "공화춘 컵라면",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "새우깡",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "신라면 컵라면",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "요맘때 콘",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "코카콜라캔",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "보석바",
            productType: "PX 간식",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
        ],
      },
      {
        boxId: "2",
        boxName: "야금야금MOA박스",
        boxPrice: 12,
        boxDescription: ["PX 냉동식품", "PC방 2천원 금액권", "카페 기프티콘"],
        boxImageUrl: "",
        productList: [
          {
            productId: "",
            productName: "슈넬치킨",
            productType: "PX 냉동식품",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "누들 그라탕",
            productType: "PX 냉동식품",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "크림우동",
            productType: "PX 냉동식품",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "짬탕면",
            productType: "PX 냉동식품",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "콤비네이션 피자",
            productType: "PX 냉동식품",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "불닭만두",
            productType: "PX 냉동식품",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "PC방 금액권 2천원",
            productType: "PC방 금액권",
            productImageUrl: "",
            exchangeStore: "제휴 PC방",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "메가커피 아메리카노",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "메가커피",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "컴포즈커피 아메리카노",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "컴포즈커피",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "이디야커피 아메리카노",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "이디야커피",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "더벤티 아메리카노",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "더벤티",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "빽다방 아메리카노",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "빽다방",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
        ],
      },
      {
        boxId: "3",
        boxName: "왕창MOA박스",
        boxPrice: 20,
        boxDescription: ["PX 50% 할인권", "PC방 2천원 금액권", "카페 기프티콘"],
        boxImageUrl: "",
        productList: [
          {
            productId: "",
            productName: "PC방 금액권 5천원",
            productType: "PC방 금액권",
            productImageUrl: "",
            exchangeStore: "제휴 PC방",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "PX 할인권 50%",
            productType: "PX 할인권",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "스타벅스 아메리카노",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "스타벅스",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "스타벅스 가나슈 케이크",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "스타벅스",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "스타벅스 레드벨벳 케이크",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "스타벅스",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "투썸 아메리카노",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "투썸플레이스",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "투썸 딸기 초코 생크림",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "투썸플레이스",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "투썸 아이스박스",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "투썸플레이스",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "투썸 티라미수",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "투썸플레이스",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "베스킨라빈스 파인트",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "베스킨라빈스",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "공차 블랙밀크티 w펄",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "공차",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
        ],
      },
      {
        boxId: "4",
        boxName: "영끌MOA박스",
        boxPrice: 30,
        boxDescription: [
          "PX 1만원 금액권",
          "PC방 1만원 금액권",
          "치킨, 피자 기프티콘",
        ],
        boxImageUrl: "",
        productList: [
          {
            productId: "",
            productName: "PC방 금액권 1만원",
            productType: "PC방 금액권",
            productImageUrl: "",
            exchangeStore: "제휴 PC방",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "PX 금액권 1만원",
            productType: "PX 금액권",
            productImageUrl: "",
            exchangeStore: "부대 안 PX",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "in",
          },
          {
            productId: "",
            productName: "교촌치킨 허니콤보",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "교촌치킨",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "BBQ 황금올리브 반반",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "BBQ",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "bhc 뿌링클 치킨",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "bhc",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "푸라닭 고추마요치킨",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "푸라닭",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "굽네 고추바사삭",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "굽네",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "네네 스노윙치킨",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "네네",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "도미노 베스트콰트로피자",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "도미노",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "도미노 블랙타이거슈림프",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "도미노",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "피자헛 티본스테이크피자",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "피자헛",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
          {
            productId: "",
            productName: "피자헛 블랙알리오 피자",
            productType: "기프티콘",
            productImageUrl: "",
            exchangeStore: "피자헛",
            expiryDate: "",
            barcodeNum: "",
            armyInOut: "out",
          },
        ],
      },
    ]);
  }
  return (
    <BoxListData.Provider value={{ boxList }}>{children}</BoxListData.Provider>
  );
}

export default BoxList;
